version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/store
      - BOT_TOKEN=7015932948:AAHPjrZxk6X8BwNoJVfR9_DX3eHQwkPSdjw
      - APP_HOST=https://127.0.0.1
      - APP_PORT=8000
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: